// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCquvqUKSUXTpXuBoIpL4VD4QB4WUbmQmY',
    appId: '1:857760577239:web:d78207c7439812e391e292',
    messagingSenderId: '857760577239',
    projectId: 'accessory-hub-e6560',
    authDomain: 'accessory-hub-e6560.firebaseapp.com',
    storageBucket: 'accessory-hub-e6560.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAWRACKIpGQpV64SpX7uBeW3odOtNLub4',
    appId: '1:857760577239:android:21e7a743f317504691e292',
    messagingSenderId: '857760577239',
    projectId: 'accessory-hub-e6560',
    storageBucket: 'accessory-hub-e6560.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFqAJuUqgyjf0ALBOzTybMtpfjtbKREIg',
    appId: '1:857760577239:ios:d4a2215ac714acfe91e292',
    messagingSenderId: '857760577239',
    projectId: 'accessory-hub-e6560',
    storageBucket: 'accessory-hub-e6560.firebasestorage.app',
    iosBundleId: 'com.example.accessoryHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFqAJuUqgyjf0ALBOzTybMtpfjtbKREIg',
    appId: '1:857760577239:ios:d4a2215ac714acfe91e292',
    messagingSenderId: '857760577239',
    projectId: 'accessory-hub-e6560',
    storageBucket: 'accessory-hub-e6560.firebasestorage.app',
    iosBundleId: 'com.example.accessoryHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCquvqUKSUXTpXuBoIpL4VD4QB4WUbmQmY',
    appId: '1:857760577239:web:8c5daaa02d975ae691e292',
    messagingSenderId: '857760577239',
    projectId: 'accessory-hub-e6560',
    authDomain: 'accessory-hub-e6560.firebaseapp.com',
    storageBucket: 'accessory-hub-e6560.firebasestorage.app',
  );
}
